# Imports

In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
import sys

sys.path.insert(0, 'code/')

In [6]:
import h5py
import numpy as np

import torch
import torch
from torch import nn
from torch.utils.data import DataLoader
import torchvision
from torchsummaryX import summary

from tqdm import tqdm_notebook as tqdm

from mac import MACNetwork
from utils import load_vocab
from datasets import ClevrDataset, collate_fn

In [7]:
from config import cfg_from_file, __C, cfg

cfg_from_file('cfg/local.yml')
__C.CUDA = False
__C.GPU_ID = '-1'
vocab = load_vocab(cfg)
# cfg.TRAIN.RECV_OBJECTS = False

code/config.py:83: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))


In [9]:
model = MACNetwork(cfg=cfg, max_step=4, vocab=vocab)
model.load_state_dict(torch.load('/Users/sebamenabar/Documents/vanilla_mac.pth', map_location='cpu')['model'])

IncompatibleKeys(missing_keys=[], unexpected_keys=[])

In [10]:
ds = ClevrDataset(
    data_dir='/Users/sebamenabar/Documents/datasets/CLEVR/data',
    split='val',
)

In [16]:
loader = DataLoader(dataset=ds, batch_size=1, shuffle=False,
                                       num_workers=2, drop_last=False, collate_fn=collate_fn)

In [17]:
b = next(iter(loader))

In [26]:
fmap = model.input_unit.stem(b['image'])

In [30]:
top = fmap[0,:,0,list(range(14))]

In [44]:
s = 4
list(range(s)) + list(range(s, s * s , s)) + list(range(2 * s - 1, s * s, s)) + list(range(s * (s - 1) + 1, s * s - 1))

[0, 1, 2, 3, 4, 8, 12, 7, 11, 15, 13, 14]

In [38]:
torch.arange(0, 16).view(4, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [33]:
top.std(dim=1)

tensor([1.7141e+00, 4.2926e-02, 2.0642e-01, 1.1241e+00, 1.2899e+00, 4.9103e-03,
        9.3407e-03, 1.4592e-01, 1.7140e+00, 8.1821e-03, 2.1487e-02, 2.7505e-03,
        1.2366e+00, 4.9992e+00, 5.8880e-03, 4.7496e-03, 5.5272e-02, 9.7728e-01,
        3.9245e+00, 7.4292e+00, 1.2187e-02, 1.7852e-02, 1.7735e-02, 1.3144e-02,
        1.6349e+00, 1.7700e-02, 2.3734e-02, 1.1015e-02, 2.5699e-03, 7.4664e-01,
        1.4580e-03, 3.8886e-03, 2.3788e-03, 4.7122e-02, 1.7201e-01, 8.0352e-02,
        2.2408e-02, 5.5633e-02, 2.7722e-02, 7.6152e-02, 1.4304e-03, 3.7584e-02,
        5.9353e-02, 5.2860e-03, 2.1467e-04, 2.2016e-03, 6.1911e-02, 6.3515e-03,
        2.2281e-02, 1.9292e-02, 6.0397e+00, 2.7573e-02, 2.0148e-03, 1.2008e-01,
        1.5899e-02, 2.5007e+00, 3.1876e-04, 1.6711e-02, 3.6776e-02, 4.5686e+00,
        4.2883e-03, 2.0316e-02, 9.5893e-02, 1.7762e-01, 9.9445e-02, 3.3912e-03,
        1.7558e-02, 7.9536e-03, 1.0071e-01, 4.1505e-02, 4.5348e-01, 1.6035e-02,
        2.1076e-02, 8.4860e-01, 1.4121e-

In [28]:
for i in range(14):
a

tensor([[ 5.4152, -0.9830, -1.0000,  ..., -0.9998, -0.9997, -1.0000],
        [-0.9940, -0.9997, -0.9758,  ..., -0.9987, -0.9998, -0.9802],
        [-1.0000, -0.9999, -0.2255,  ..., -0.9998, -0.9999, -0.9980],
        ...,
        [-0.9999, -0.9999, -0.9878,  ..., -0.9996, -0.9824, -0.9883],
        [-0.9977, -0.9310, -0.9917,  ..., -0.9993, -0.9997, -0.9725],
        [-0.9975, -0.9976, -0.9554,  ..., -0.9941, -0.9997, -0.9997]],
       grad_fn=<IndexBackward>)
tensor([[ 5.4152, -0.9830, -1.0000,  ..., -0.9998, -0.9997, -1.0000],
        [-0.9940, -0.9997, -0.9758,  ..., -0.9987, -0.9998, -0.9802],
        [-1.0000, -0.9999, -0.2255,  ..., -0.9998, -0.9999, -0.9980],
        ...,
        [-0.9999, -0.9999, -0.9878,  ..., -0.9996, -0.9824, -0.9883],
        [-0.9977, -0.9310, -0.9917,  ..., -0.9993, -0.9997, -0.9725],
        [-0.9975, -0.9976, -0.9554,  ..., -0.9941, -0.9997, -0.9997]],
       grad_fn=<IndexBackward>)
tensor([[ 5.4152, -0.9830, -1.0000,  ..., -0.9998, -0.9997, -1.0000]